version: "3.9"

services:
  laravel-app:
    build:
      args:
        user: user
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: laravel-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    depends_on:
      - redis
      - queue
      - mysql
    networks:
      - laravel-app

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - laravel-app

  mysql:
    image: mysql:latest
    restart: unless-stopped
    container_name: mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - ./.docker/mysql/dbdata:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3388:3306
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    networks:
      - laravel-app

  queue:
    build:
      args:
        user: user
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    command: "php artisan queue:work"
    volumes:
      - ./:/var/www
    depends_on:
      - redis
    networks:
      - laravel-app

  redis:
    image: redis:latest
    networks:
      - laravel-app

networks:
  laravel-app:
    driver: bridge
